[package]
name = "derive_convert"
version = "0.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Derives 'impl (Try)From for Self' and 'impl (Try)From<Self>'"
categories = ["rust-patterns"]
repository = "https://github.com/qthree/derive_convert"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"

[lib]
proc-macro = true
